name = "blood-mc"
author = "bloodwolfe"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93207ae6251228b4f482af619682ade3fad7b3bec5c442a57dc7dd26a168b594"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
