name = "bloodpack"
author = "bloodwolfe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daff7979bf61903ae6cbf83cbab0145ceebc9a4c3fa7491df5cd9fef9191fedf"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21", "1.22", "1.23"]
