name = "blood-mc"
author = "bloodwolfe"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd9dad3f08c5263aeae2a9e6e50ba98cf8c419215c843442c05172f0ab782913"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
