name = "blood-mc"
author = "bloodwolfe"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23da6d0a09c49346e850a6f37a92e6e843a2055966b2ab938a51f381f035b429"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
