name = "blood-mc"
author = "bloodwolfe"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f15d12b5f50cee354be5ef18772b606ba59d2c8f732e50110e35e836829b3b5"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
