name = "blood-mc"
author = "bloodwolfe"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9890a64b4557c14a29520a0a0fe6cbf7f3c68df1b4b3bb0f489a631e725024cb"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
