name = "blood-mc"
author = "bloodwolfe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e43d664e5b7d2a16d4b0ca9783eca118a188de042589800827b63daa69532a91"

[versions]
fabric = "0.16.9"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.19.4", "1.20.1", "1.20.2", "1.20.3", "1.20.4"]
