name = "Tadpole"
author = "bloodwolfepc"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e4401b99bfab7a32051f0e7baa2aad416fa923895ffbd68366c2d20422d5d90"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
