name = "Tadpole"
author = "bloodwolfepc"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75f437c2bbd8b3feb4fa2ec0ffcbfe9f976c34ebeddaac3848c62b39dffd39fd"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
