name = "blood-mc"
author = "bloodwolfe"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0a03533a2ea38f2755d2997c66d713d388779a41e6334a3c25c194363541f3d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
