name = "Tadpole Server"
author = "bloodwolfe"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be62144119d95983385aa2b2230dbaaaf2ca7979c4b0b0d63b9a0bed1d91be5a"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
