name = "Tadpole Server"
author = "bloodwolfe"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6849a27f79ecade7dffcfdb2991dcff5c8127975b3b40521f6714538658d8e54"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
