name = "Tadpole Server"
author = "bloodwolfe"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5905c443e1b28021977b29237638d0323c24838212ddad476dd2bd5d02337f62"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
